services:
  # -------------------------
  # Prometheus
  # -------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    user: "1001:1001"
    networks:
      - monitoring-net
    ports:
      - "9090:9090"
    healthcheck:
        test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9090/-/ready"]
        interval: 10s
        retries: 10
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  # -------------------------
  # Init Thanos volume rw
  # -------------------------
  init-thanos:
    image: alpine
    command: >
      sh -c "mkdir -p /prometheus/thanos/upload &&
             chown -R 1001:1001 /prometheus/thanos"
    volumes:
      - prometheus-data:/prometheus

  # -------------------------
  # Thanos Sidecar
  # -------------------------
  thanos_sidecar:
    image: thanosio/thanos:v0.36.1
    container_name: thanos_sidecar
    hostname: thanos-sidecar
    depends_on:
      prometheus:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - monitoring-net
    command: ["sidecar",
              "--tsdb.path=/prometheus",
              "--prometheus.url=http://prometheus:9090",
              "--objstore.config-file=/etc/thanos/bucket.yaml",
              "--grpc-address=0.0.0.0:10901",
              "--http-address=0.0.0.0:10902"]
    volumes:
      - prometheus-data:/prometheus
      - ./thanos/bucket.yaml:/etc/thanos/bucket.yaml:ro
      - ./thanos/generate-bucket.sh:/etc/thanos/generate-bucket.sh:ro
      - ./thanos/bucket.yaml.template:/etc/thanos/bucket.yaml.template:ro
    restart: unless-stopped

  # -------------------------
  # Thanos Querier
  # -------------------------
  thanos_querier:
    image: thanosio/thanos:v0.36.1
    container_name: thanos_querier
    hostname: thanos-querier
    networks:
      - monitoring-net
    ports:
      - "10903:10903"
    depends_on:
      - thanos_sidecar
    command: ["query",
        "--http-address=0.0.0.0:10903",
        "--log.level=info",
        "--store=thanos-sidecar:10901"]
    restart: unless-stopped

  thanos_compactor:
    image: thanosio/thanos:v0.36.1
    container_name: thanos_compactor
    hostname: thanos-compactor
    user: "0:0"
    networks:
      - monitoring-net
    command:
      - compact
      - --data-dir=/data
      - --objstore.config-file=/etc/thanos/bucket.yaml
      - --wait
    volumes:
      - ./thanos/bucket.yaml:/etc/thanos/bucket.yaml:ro
      - thanos-compactor-data:/data
    restart: unless-stopped

  # -------------------------
  # MinIO (local objectstorage)
  # -------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    networks:
      - monitoring-net
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data
    volumes:
      - minio-data:/data
    restart: unless-stopped

  # -------------------------
  # mc
  # -------------------------
  mc:
    image: minio/mc
    container_name: mc
    hostname: mc
    networks:
      - monitoring-net
    restart: "no"
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: ["/mc-entrypoint.sh"]
    volumes:
      - ./mc-entrypoint.sh:/mc-entrypoint.sh:ro

  # -------------------------
  # Grafana
  # -------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:
      - monitoring-net
    ports:
      - "3000:3000"
    environment:
        - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  # -------------------------
  # Node Exporter
  # -------------------------
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    hostname: node-exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
      - /sys:/sys:ro
      - /proc:/proc:ro
      - hvac-data:/var/lib/node_exporter/textfile_collector
    command:
      - --path.rootfs=/host
      - --collector.hwmon
      - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
    restart: unless-stopped

  # -------------------------
  # Smartctl Exporter
  # -------------------------
  smartctl_exporter:
    image: matusnovak/prometheus-smartctl:latest
    container_name: smartctl_exporter
    hostname: smartctl-exporter
    networks:
      - monitoring-net
    privileged: true
    restart: unless-stopped

  # -------------------------
  # cAdvisor
  # -------------------------
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    networks:
      - monitoring-net
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped

  # -------------------------
  # HVAC Exporter
  # -------------------------
  hvac_exporter:
    build:
      context: ./textfile_exporter
    container_name: hvac_exporter
    hostname: hvac-exporter
    networks:
      - monitoring-net
    environment:
      HVAC_IP: ${HVAC_IP}
    volumes:
      - hvac-data:/data
    restart: unless-stopped

  # -------------------------
  # Telegraf (Modbus -> Prometheus)
  # -------------------------
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    networks:
      - monitoring-net
    depends_on:
      - prometheus
    environment:
      HVAC_IP: ${HVAC_IP}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  # -------------------------
  # APC UPS Exporter
  # -------------------------
  apcupsd_exporter:
    build:
      context: ./apcupsd_exporter
    container_name: apcupsd_exporter
    hostname: apcupsd-exporter
    ports:
      - "9162:9162"
    environment:
      APC_ADDRESS: ${APC_ADDRESS}
      TELEMETRY_ADDR: :9102
    restart: unless-stopped

  # -------------------------
  # MySQLd Exporter
  # -------------------------
  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    hostname: mysqld-exporter
    networks:
      - monitoring-net
      - meterloggerweb_default
    env_file:
      - .env
    volumes:
      - ./mysqld_exporter/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysqld_exporter/entrypoint.sh:/entrypoint.sh:ro
      - ./mysqld_exporter/custom_queries.yml:/etc/mysqld_exporter/custom_queries.yml:ro
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped

  # -------------------------
  # Mosquitto Exporter
  # -------------------------
  mosquitto_exporter:
    image: sapcc/mosquitto-exporter:latest
    container_name: mosquitto_exporter
    hostname: mosquitto-exporter
    networks:
      - monitoring-net
    command:
      - --endpoint=tcp://10.0.1.6:1883
      - --bind-address=0.0.0.0:9234
    restart: unless-stopped

  # -------------------------
  # SNMP Exporter
  # -------------------------
  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    hostname: snmp-exporter
    networks:
      - monitoring-net
    ports:
      - "9116:9116"
    volumes:
      - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    restart: unless-stopped

# -------------------------
# Volumes
# -------------------------
volumes:
  grafana-data:
  prometheus-data:
  hvac-data:
  minio-data:
  thanos-compactor-data:

# -------------------------
# Networks
# -------------------------
networks:
  monitoring-net:
  meterloggerweb_default:
    external: true
