[agent]
  interval = "10s"
  round_interval = true

[[inputs.modbus]]
  name = "hvac"
  controller = "tcp://${HVAC_IP}:502"
  timeout = "5s"

########################################################
# RAW VALUES (INPUT REGISTERS - FC4)
########################################################

[[inputs.modbus.input_registers]]
  name = "co2"
  address = [100]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "supply_air_volume"
  address = [94]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "exhaust_air_volume"
  address = [95]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "cooling"
  address = [32]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "heat_exchanger"
  address = [35]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "heating"
  address = [39]
  data_type = "UINT16"
  scale = 1.0
  byte_order = "AB"

########################################################
# TEMPERATURES
########################################################

[[inputs.modbus.input_registers]]
  name = "outside_air_temp"
  address = [71]
  data_type = "INT16"
  scale = 0.1
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "supply_air_temp"
  address = [72]
  data_type = "INT16"
  scale = 0.1
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "room_temp"
  address = [74]
  data_type = "INT16"
  scale = 0.1
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "return_air_temp"
  address = [75]
  data_type = "INT16"
  scale = 0.1
  byte_order = "AB"

[[inputs.modbus.input_registers]]
  name = "exhaust_air_temp"
  address = [76]
  data_type = "INT16"
  scale = 0.1
  byte_order = "AB"

########################################################
# OUTPUT
########################################################

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
